variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build_docker_image: 
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:0.0.1 .
    - docker push $CI_REGISTRY_IMAGE:0.0.1
  after_script:
    - docker logout ${CI_REGISTRY}

hx-production:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
     - sed -i s#%DOCKER_IMAGE%#$CI_REGISTRY_IMAGE\:0.0.1#g k8s-deployment.yaml
     - export KUBECONFIG=/home/gitlab-runner/.kube/hx-wp-webadmin-01-team-admin &&  kubectl apply -f k8s-deployment.yaml

hh-production:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
     - sed -i s#%DOCKER_IMAGE%#$CI_REGISTRY_IMAGE\:0.0.1#g k8s-deployment.yaml
     - export KUBECONFIG=/home/gitlab-runner/.kube/hh-wp-webadmin-01-team-admin &&  kubectl apply -f k8s-deployment.yaml
